spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mariadb://20.214.203.241:3306/IHVMS
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate