spring:
  profiles:
    active: local
  messages:
    basename: messages/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
server:
  error:
    path: /error
