spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mariadb://20.214.203.241:3306/IHVMS
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
        "[globally_quoted_identifiers]": true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      #create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
      #create-drop: create와 같으나 종료시점에 테이블 DROP
      #update: 변경분만 반영(운영DB에서는 사용하면 안됨)
      #validate: 엔티티와 테이블이 정상 매핑되었는지만 확인
      #none: 사용하지 않음(사실상 없는 값이지만 관례상 none이라고 한다.)
      naming:
        #논리적 명명 전략
        #implicit-strategy:
        #물리적 명명 전략
        physical-strategy: kr.or.i815.ihvms.configuration.CustomNamingStrategy

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace